JoyPiAdvanced.initializeAdvanced()
JoyPiAdvanced.tftInit()
JoyPiAdvanced.tftOn()

JoyPiAdvanced.tftClear()
basic.pause(1000)

JoyPiAdvanced.tftDrawPixel(10, 10, JoyPiAdvancedTFTColor.red)
basic.pause(1000)

JoyPiAdvanced.tftClear()
JoyPiAdvanced.tftDrawLine(0, 0, JoyPiAdvanced.tftGetWidth(), JoyPiAdvanced.tftGetHeight(), JoyPiAdvancedTFTColor.green)
basic.pause(1000)

JoyPiAdvanced.tftClear()
JoyPiAdvanced.tftDrawRectangle(10, 10, JoyPiAdvanced.tftGetWidth() - 10, JoyPiAdvanced.tftGetHeight() - 10, JoyPiAdvancedTFTColor.blue)
JoyPiAdvanced.tftFillRectangle(20, 20, JoyPiAdvanced.tftGetWidth() - 30, JoyPiAdvanced.tftGetHeight() - 30, JoyPiAdvancedTFTColor.yellow)
basic.pause(1000)

JoyPiAdvanced.tftClear()
JoyPiAdvanced.tftDrawCircle(JoyPiAdvanced.tftGetWidth() / 2, JoyPiAdvanced.tftGetHeight() / 2, 30, JoyPiAdvancedTFTColor.cyan)
JoyPiAdvanced.tftFillCircle(JoyPiAdvanced.tftGetWidth() / 2, JoyPiAdvanced.tftGetHeight() / 2, 20, JoyPiAdvancedTFTColor.magenta)
basic.pause(1000)

JoyPiAdvanced.tftClear()
JoyPiAdvanced.tftShowString("TFT Test", 10, 10, 2, JoyPiAdvancedTFTColor.white, JoyPiAdvancedTFTColor.black)
basic.pause(1000)

JoyPiAdvanced.tftClear()
JoyPiAdvanced.tftFillTriangle(10, 10, JoyPiAdvanced.tftGetWidth() - 10, JoyPiAdvanced.tftGetHeight() - 10, JoyPiAdvanced.tftGetWidth() / 2, JoyPiAdvanced.tftGetHeight() / 2, JoyPiAdvancedTFTColor.orange)
basic.pause(1000)

JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.black)
basic.pause(100)
JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.navy)
basic.pause(100)
JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.darkgreen)
basic.pause(100)
JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.darkcyan)
basic.pause(100)
JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.maroon)
basic.pause(100)
JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.purple)
basic.pause(100)
JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.olive)
basic.pause(100)
JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.lightGrey)
basic.pause(100)
JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.darkGrey)
basic.pause(100)
JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.greenyellow)
basic.pause(100)
JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.pink)
basic.pause(100)
JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.gold)
basic.pause(100)
JoyPiAdvanced.tftFill(JoyPiAdvancedTFTColor.brown)
basic.pause(100)

JoyPiAdvanced.tftClear()
JoyPiAdvanced.tftOff()